apiVersion: v1
kind: Service
metadata:
  name: fortistack-service
  namespace: fortistack
spec:
  type: LoadBalancer
  selector:
    app: fortistack-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
